name: Check Repository Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: チェック: GITHUB_TOKEN が設定されているか
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "❌ GITHUB_TOKEN が設定されていません。"
            exit 1
          else
            echo "✅ GITHUB_TOKEN が正しく設定されています。"
          fi
