name: Check Repository Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: "チェック: TOKEN_FOR_SETTINGS_TEST_REPOSITORY が設定されているか?"
        run: |
          if [ -z "${{ secrets.TOKEN_FOR_SETTINGS_TEST_REPOSITORY }}" ]; then
            echo "❌ TOKEN_FOR_SETTINGS_TEST_REPOSITORY が設定されていません。"
            exit 1
          else
            echo "✅ TOKEN_FOR_SETTINGS_TEST_REPOSITORY が正しく設定されています。"
          fi
